"""SQLite-backed repository for AML alert tickets.

Stores tickets generated by the Kafka consumer/ML inference pipeline.
Database file: backend/data/tickets.db (auto-created on first use).
"""

import json
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from app.schemas.ticket import (
    TicketCreate,
    TicketResponse,
    TicketStatus,
    TicketStatsResponse,
)

# Default DB path: backend/data/tickets.db
_DEFAULT_DB_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "tickets.db"

_CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS tickets (
    ticket_id     TEXT PRIMARY KEY,
    transaction_id TEXT NOT NULL,
    confidence    REAL NOT NULL,
    is_suspicious INTEGER NOT NULL,
    status        TEXT NOT NULL,
    transaction_data TEXT NOT NULL,
    created_at    TEXT NOT NULL
);
"""

_INSERT_SQL = """
INSERT INTO tickets (ticket_id, transaction_id, confidence, is_suspicious, status, transaction_data, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?);
"""


class TicketRepository:
    """Thread-safe SQLite ticket store."""

    def __init__(self, db_path: Optional[Path] = None):
        self._db_path = str(db_path or _DEFAULT_DB_PATH)
        # Ensure parent directory exists
        Path(self._db_path).parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._init_db()

    # ── helpers ──────────────────────────────────────────────────────────
    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self._db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.execute(_CREATE_TABLE_SQL)
            conn.commit()

    def _next_ticket_id(self, conn: sqlite3.Connection) -> str:
        row = conn.execute("SELECT COUNT(*) AS cnt FROM tickets").fetchone()
        seq = (row["cnt"] if row else 0) + 1
        return f"TICKET-{seq:05d}"

    @staticmethod
    def _row_to_response(row: sqlite3.Row) -> TicketResponse:
        return TicketResponse(
            ticket_id=row["ticket_id"],
            transaction_id=row["transaction_id"],
            confidence=row["confidence"],
            is_suspicious=bool(row["is_suspicious"]),
            status=TicketStatus(row["status"]),
            transaction_data=json.loads(row["transaction_data"]),
            created_at=datetime.fromisoformat(row["created_at"]),
        )

    # ── public API ──────────────────────────────────────────────────────
    def create_ticket(self, data: TicketCreate) -> TicketResponse:
        """Insert a new ticket and return the created record."""
        now = datetime.now(timezone.utc)
        with self._lock:
            with self._connect() as conn:
                ticket_id = self._next_ticket_id(conn)
                conn.execute(
                    _INSERT_SQL,
                    (
                        ticket_id,
                        data.transaction_id,
                        data.confidence,
                        int(data.is_suspicious),
                        data.status.value,
                        json.dumps(data.transaction_data, default=str),
                        now.isoformat(),
                    ),
                )
                conn.commit()
        return TicketResponse(
            ticket_id=ticket_id,
            transaction_id=data.transaction_id,
            confidence=data.confidence,
            is_suspicious=data.is_suspicious,
            status=data.status,
            transaction_data=data.transaction_data,
            created_at=now,
        )

    def get_ticket(self, ticket_id: str) -> Optional[TicketResponse]:
        """Retrieve a single ticket by ID."""
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM tickets WHERE ticket_id = ?", (ticket_id,)
            ).fetchone()
        return self._row_to_response(row) if row else None

    def get_tickets(
        self,
        status: Optional[TicketStatus] = None,
        page: int = 1,
        page_size: int = 20,
    ) -> tuple[list[TicketResponse], int]:
        """Return a paginated list of tickets, optionally filtered by status."""
        where = ""
        params: list = []
        if status:
            where = "WHERE status = ?"
            params.append(status.value)

        with self._connect() as conn:
            total = conn.execute(
                f"SELECT COUNT(*) AS cnt FROM tickets {where}", params
            ).fetchone()["cnt"]

            offset = (page - 1) * page_size
            rows = conn.execute(
                f"SELECT * FROM tickets {where} ORDER BY created_at DESC LIMIT ? OFFSET ?",
                params + [page_size, offset],
            ).fetchall()

        return [self._row_to_response(r) for r in rows], total

    def get_stats(self) -> TicketStatsResponse:
        """Return aggregate dashboard statistics."""
        with self._connect() as conn:
            row = conn.execute("""
                SELECT
                    COUNT(*)                           AS total_tickets,
                    SUM(CASE WHEN status='WARNING'   THEN 1 ELSE 0 END) AS warning_count,
                    SUM(CASE WHEN status='DANGEROUS' THEN 1 ELSE 0 END) AS dangerous_count,
                    AVG(confidence)                    AS avg_confidence,
                    MAX(created_at)                    AS latest_ticket_at
                FROM tickets
            """).fetchone()

        latest = (
            datetime.fromisoformat(row["latest_ticket_at"])
            if row["latest_ticket_at"]
            else None
        )
        return TicketStatsResponse(
            total_tickets=row["total_tickets"] or 0,
            warning_count=row["warning_count"] or 0,
            dangerous_count=row["dangerous_count"] or 0,
            avg_confidence=round(row["avg_confidence"] or 0.0, 4),
            latest_ticket_at=latest,
        )

    def clear_all(self) -> int:
        """Delete all tickets. Returns the number of deleted rows."""
        with self._lock:
            with self._connect() as conn:
                cursor = conn.execute("DELETE FROM tickets")
                conn.commit()
                return cursor.rowcount


# ── Singleton instance ──────────────────────────────────────────────────
_instance: Optional[TicketRepository] = None


def get_ticket_repository() -> TicketRepository:
    """Return the global singleton TicketRepository."""
    global _instance
    if _instance is None:
        _instance = TicketRepository()
    return _instance
